CREATE TABLE IF NOT EXISTS customer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    address TEXT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

INSERT INTO customer (first_name, last_name, email, address, created_at)
VALUES
('James', 'Bond', 'james@gmail.com', 'London UK', '2020-11-24 23:42:47.000000'),
('Ali', 'Ahmed', 'ali@gmail.com', 'Florida USA', '2022-11-24 23:42:47.000000'),
('Jamila', 'Bah', 'jamila@gmail.com', 'Dubai UK', '2022-11-24 23:42:47.000000'),
('Ana', 'Maria', 'anamaria@gmail.com', 'Madrid UK', '2021-11-24 23:42:47.000000');

CREATE TABLE IF NOT EXISTS customer_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT REFERENCES customer(id) NOT NULL,
    total_amount NUMERIC(10, 2) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

INSERT INTO customer_order (customer_id, total_amount, created_at)
VALUES
(1, 2.00, '2020-11-24 23:42:47.000000'),
(2, 3.50, '2020-11-24 23:42:47.000000'),
(3, 0.50, '2020-11-24 23:42:47.000000'),
(3, 5.00, '2020-11-24 23:42:47.000000');

CREATE TABLE IF NOT EXISTS order_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES product(id) NOT NULL,
    order_id BIGINT REFERENCES customer_order(id) NOT NULL,
    quantity INT NOT NULL CHECK(quantity > 0),
    price NUMERIC(10, 2) NOT NULL
);

INSERT INTO order_item (product_id, order_id, quantity, price)
VALUES
(1, 1, 4, 1.00),
(3, 2, 1, 1.00),
(4, 2, 1, 2.50),
(1, 3, 1, 0.50),
(4, 4, 2, 5.00);

CREATE TABLE IF NOT EXISTS product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    discounted BOOLEAN NOT NULL
);

INSERT INTO product (name, price, discounted)
VALUES
('bread', 0.50, false),
('sugar', 0.75, true),
('milk', 1.00, false),
('brownie', 2.50, false),
('ice-cream', 2.00, false),
('pepsi', 0.50, true);

CREATE TABLE IF NOT EXISTS accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    balance NUMERIC(19, 2) NOT NULL
);

INSERT INTO accounts (name, balance)
VALUES
('James', 1000),
('Jamila', 10000);